### ISSUE TITLE
Different damage types

### ISSUE THREAD

**Issue by paladinkolovrat** [isathar/F4SE_F4TF_DamageTweaks#1]
Will mod support diff damage types like it was in FO1 and FO2?

Nice job, anyway! And AmmoTweaks and patcher and this now - awesome!

**Comment by isathar** [comment]
Thanks! And yep, Just about everything related to damage from the classic Fallout games and FNV is there. I just need to finish up the critical hit tables and it should be set for a test release.

**Comment by isathar** [comment]
To add on to that vague response:
All the unused damage types in Fallout 4 are supported, and you can add your own. There's a plugin that adds a few custom damage types as examples, including Laser and Plasma from the originals. I still need to separate the inventory menu stuff from AmmoTweaks to actually be able to see custom types somewhere, though.

There are a few options to specify which DR formula to use (classic percentage-based or Fallout 4's weird exponent-based math) and changing the order in which things are applied. All constants are also exposed to a config file for easy tweaking. A side-effect of re-creating Fallout 4's formula is that the weirdness with energy resistance is fixed. Another one is that the Mod Target DR perk entry point no longer works, but also isn't actually needed anymore.

It also includes Damage Threshold, with options to use one value (FNV style) or different values for each damage type (classic style). There's an option to move DT to the beginning or end of the calculations.

Armor condition is in, too, although it's not all that useful without CND affecting stats, the inventory menu stuff, or the repair kits from AmmoTweaks.

I'm currently working on moving and converting the critical hit tables I made for AmmoTweaks 2.0 to be based on the target's race and actor keywords, and will post something once it's stable.

**Comment by paladinkolovrat** [comment]
Thank you for explaining
